import { Actor } from './actor'
import { Event } from './events'

export enum ItemKind {
    AVALANCHE = 'Avalanche',
    BIG_CLUB = 'Big Club',
    BF_CANNON = 'BF Cannon',
    BOOSTING_BUGLE = 'Boosting Bugle',
    CHALLENGER_ARROW = 'Challenger Arrow',
    CHICKEN_HEALING = 'Dummy Chicken Healing',
    CHUMBY_CHICKEN = 'Chumby Chicken',
    CLEANSING_FLAMES = 'Cleansing Flames',
    DRAINING_DAGGER = 'Draining Dagger',
    ENERGETIC_ALLY = 'Energetic Ally',
    EXPLOSION_POWDER = 'Explosion Powder',
    FESTIVE_FEAST = 'Festive Feast',
    FIRE_SWORD = 'Fire Sword',
    FREEZEMAN = 'Freezeman',
    HALBERD = 'Halberd',
    HEALING_PENDANT = 'Healing Pendant',
    IMP_WHISTLE = 'Imp Whistle',
    KNIGHTS_LANCE = 'Knight\'s Lance',
    LOVE_LETTER = 'Love Letter',
    MACHETE = 'Machete',
    MARTYR_ARMOR = 'Martyr Armor',
    MAGIC_PARASOL = 'Magic Parasol',
    PET_IMP = 'Pet Imp',
    POISON_DAGGER = 'Poison Dagger',
    ROCK_COMPANION = 'Rock Companion',
    ROUGH_SKIN = 'Rough Skin',
    SEEKING_MISSILES = 'Seeking Missiles',
    SURVIVAL_KIT = 'Survival Kit',
    THORNS = 'Thorns',
    TRUSTY_STEED = 'Trusty Steed',
    WHIRLWIND_AXE = 'Whirlwind Axe',
    NONE = 'None'
}